### ISSUE TITLE
Arrows for carousel

### ISSUE THREAD

**Issue by jkosem** [halfman-ltd/gates-of-vienna-wp#1]

**Comment by jkosem** [comment]
![screen shot 2015-01-08 at 17 01 25](https://cloud.githubusercontent.com/assets/495102/5666522/0684e334-9758-11e4-8b1f-7011d92dd283.png)
Arrows are showing up below the carousel. Also, can you make them bigger or show me how to size them?

**Comment by lukeshumard** [comment]
Huh, weird. Which browser? Seems to be working in all of mine?

**Comment by jkosem** [comment]
Safari


--
Jim Kosem
+44 7757 559081

**Comment by lukeshumard** [comment]
Okay, going to fix in 15. Should be a quick one.

**Comment by lukeshumard** [comment]
Fixed!
