### ISSUE TITLE
Footer not exactly sticky

### ISSUE THREAD

**Issue by jkosem** [halfman-ltd/gates-of-vienna-wp#12]
![screen shot 2014-12-10 at 14 30 32](https://cloud.githubusercontent.com/assets/495102/5377358/4498ca46-8079-11e4-8718-fbb7b26f5737.png)

**Comment by lukeshumard** [comment]
I fucking fixed it no way.

**Comment by jkosem** [comment]
You fucking dick. Window load, not document ready.
