### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by jkosem** [halfman-ltd/gates-of-vienna-wp#16]
I should do this.

**Comment by jkosem** [comment]
Like this? Its in Dropbox as well by the way.

![home](https://cloud.githubusercontent.com/assets/495102/5929171/37736a08-a679-11e4-8c65-d68fbdf6bbe3.png)

![post](https://cloud.githubusercontent.com/assets/495102/5929175/3cf5a964-a679-11e4-8a30-cf80dfd98a8b.png)

![archive](https://cloud.githubusercontent.com/assets/495102/5929178/419193ca-a679-11e4-9dee-8ec62a62c1ad.png)

**Comment by jkosem** [comment]
@lukeshumard What do you think? Enough to finish?

**Comment by lukeshumard** [comment]
Yeah, looking good! I'm gonna crush this.
