### ISSUE TITLE
Fix text-sizing on pitch + intro

### ISSUE THREAD

**Issue by jkosem** [halfman-ltd/gates-of-vienna-wp#17]
![screen shot 2015-01-13 at 22 34 13](https://cloud.githubusercontent.com/assets/495102/5730683/589e41fe-9b74-11e4-9100-8a42f492ad68.png)

**Comment by jkosem** [comment]
And for about the author and about the project.

**Comment by lukeshumard** [comment]
Done

**Comment by jkosem** [comment]
body {
  font-size: 18px;
  line-height: 24px;
  max-width: 760px;
  margin: 0 auto;
}
h1 {
  font-size: 101px;
  line-height: 120px;
  margin-top: 48px;
  margin-bottom: 24px;
}
h2 {
  font-size: 57px;
  line-height: 72px;
  margin-top: 48px;
  margin-bottom: 24px;
}
h3 {
  font-size: 32px;
  line-height: 48px;
  margin-top: 24px;
  margin-bottom: 24px;
}
h4 {
  font-size: 18px;
  line-height: 24px;
  margin-top: 24px;
  margin-bottom: 24px;
}
p, ul, ol, pre, table, blockquote {
  margin-top: 24px;
  margin-bottom: 24px;
}

/* Sanitation */
hr {
  border: 1px solid;
  margin: -1px 0;
}
ul ul, ol ol, ul ol, ol ul {
  margin-top: 0;
  margin-bottom: 0;
}
b, strong, em, small, code {
  line-height: 1;
}
sup, sub {
  vertical-align: baseline;
  position: relative;
  top: -0.4em;
}
sub {
  top: 0.4em;
}

**Comment by jkosem** [comment]
Basically its like this
https://www.dropbox.com/s/dlvw8nk7ltbjmdh/webpage.1.3.sketch?dl=0

**Comment by lukeshumard** [comment]
Can I get a screengrab of this as well, please?

**Comment by jkosem** [comment]
![home](https://cloud.githubusercontent.com/assets/495102/6059314/fa60c6a0-ad27-11e4-83a1-ca6cbc2eae41.png)
