### ISSUE TITLE
Index carousel arrows on hover?

### ISSUE THREAD

**Issue by jkosem** [halfman-ltd/gates-of-vienna-wp#20]
On https://www.dropbox.com/s/dlvw8nk7ltbjmdh/webpage.1.3.sketch?dl=0 I've got fancy bluish arrows. How about putting them on hover?

**Comment by lukeshumard** [comment]
Can you send a screenshot? My Sketch won't open.

**Comment by jkosem** [comment]
![home](https://cloud.githubusercontent.com/assets/495102/6059304/d219f374-ad27-11e4-8753-050434fee03e.png)

**Comment by jkosem** [comment]
By the way, do you have a current copy of Sketch or is there a problem with the file?

**Comment by lukeshumard** [comment]
I have Sketch 3, which I'm pretty sure is that latest. No idea why it's not opening :(

**Comment by jkosem** [comment]
Still having problems with Sketch? Maybe update it? I know they’ve pushed a bunch of updates kind of recently.

--
Jim Kosem
+44 7757 559081
