### ISSUE TITLE
Updating plugins, etc. in WP admin

### ISSUE THREAD

**Issue by jkosem** [halfman-ltd/gates-of-vienna-wp#23]
Just wondering if I should just go ahead and update shit as it starts throwing notifications at me or will everything potentially implode. It used to be like this with some other WP stuff I did with people.

**Comment by lukeshumard** [comment]
I mean, you can do this stuff, but the risk of potential implosion is there. I've tried to make sure it's mostly free of plugins, but the ones it does use are...
+ Advanced Custom Fields Pro
+ Amazon AWS Helpers (for use with S3 plugin)
+ S3 and Cloudfront (puts all of your images and shit on S3)

We'll keep the dev site up in parallel to the production site, so test it all out on the dev site first before doing it on the production / live version.

**Comment by jkosem** [comment]
Okay cheers. You never know, this shit can be mad temperamental.
