### ISSUE TITLE
Moving the newsletter to below the carousel

### ISSUE THREAD

**Issue by jkosem** [halfman-ltd/gates-of-vienna-wp#4]
Did this in the HTML myself, so don't know if you want to do this or I could just wait till you got it all sorted. Let me know.

**Comment by lukeshumard** [comment]
Is this right? Doesn't seem quite right there.
http://dev-gatesofvienna.nonement.com/

**Comment by jkosem** [comment]
Yeah, not great is it? It relates more to the blog so thats why I was thinking of putting it there. What do yo think?

The main point of even having a newsletter though is to try and get build up to some sort of launch and have some vague idea as to how many people are interested or would potentially pay for this thing. However, I was thinking of just having the blog posts go through Mailchimp as well, but maybe that isn't the greatest idea in the world.

**Comment by lukeshumard** [comment]
I'm a little confused, so let's talk about this when we meet next.
